{% set name = "farmOS" %}
{% set version = "1.0.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b92f8d1500d8ad399a3537b6d56e4862329bbdb8814c6a7ab4eeb97a6a5f79c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pytest-runner
    - pip
  run:
    - python >=3
    - requests-oauthlib
    - pydantic >=1.7.3

test:
  imports:
    - farmOS
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/farmOS/farmOS.py
  license: GPL-3.0-only
  license_file: LICENSE
  summary: 'A Python library for interacting with farmOS over API.'

extra:
  recipe-maintainers:
    - paul121
